[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "./bin/polkadot"
default_args = [ "-lparachain=debug" ]

    [[relaychain.nodes]]
    name = "alice"
    validator = true
    ws_port = 9944

    [[relaychain.nodes]]
    name = "bob"
    validator = true

    [[relaychain.nodes]]
    name = "charlie"
    validator = true

[[parachains]]
id = 1337
addToGenesis = true
cumulus_based = true

    [parachains.collator]
    name = "oracle-collator"
    command = "./bin/parachain-template-node"
    ws_port = 9955

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
